---
title: "Week_5_prac"
output: html_document
date: "2023-11-03"
---

## 1.1 spatial joining
```{r}
library(sf)

Londonborough <- st_read(here::here("Week_5_prac","statistical-gis-boundaries-london",
                                    "ESRI","London_Borough_Excluding_MHW.shp")) %>%
  st_transform(.,27700)

```
```{r}
OSM <- st_read(here::here("Week_5_prac","greater-london-latest-free.shp",
               "gis_osm_pois_free_1.shp")) %>%
  st_transform(.,27700) %>%
  dplyr::filter(fclass == "hotel")
``` 
```{r}
join_example <- st_join(Londonborough, OSM)

head(join_example)
```

## 1.2 static map
```{r}
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)
```
```{r}
OSM <- st_read(here::here("Week_5_prac",
                          "greater-london-latest-free.shp",
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  filter(fclass == "hotel")
```
```{r}
worldcities <- st_read(here::here("Week_5_prac",
                                  "World_Cities",
                                  "World_Cities.shp")) %>%
  st_transform(.,27700)
```
```{r}
UK_outline <- st_read(here::here("Week_5_prac",
                                 "gadm41_GBR_shp",
                                 "gadm41_GBR_0.shp")) %>%
  st_transform(., 27700)
```
```{r}
Londonborough <- st_read(here::here("Week_5_prac",
                                    "statistical-gis-boundaries-london",
                                    "ESRI",
                                    "London_Borough_Excluding_MHW.shp")) %>%
  st_transform(., 27700)
```
```{r}
# read in the csv and make it into spatial data
# longitude is considered x value, latitude is y
Airbnb <- read_csv(here::here("Week_5_prac",
                              "listings.csv")) %>%
  st_as_sf(., coords = c("longitude","latitude"),
           crs = 4326) %>%
  st_transform(., 27700) %>%
  filter(room_type == "Entire home/apt" & availability_365 == "365")
```
```{r}
# make a function
Joinfun <- function(data1, data2){

output<- data1%>%
  st_join(data2,.) %>%
  add_count(GSS_CODE, name="hotels_in_borough") 

  return(output)
}
```
```{r}
Hotels <- Joinfun(OSM, Londonborough)
Airbnb <- Joinfun(Airbnb, Londonborough)
```
```{r}
worldcities2 <- worldcities %>%
  filter(CITY_NAME == "Birmingham"|
           CITY_NAME == "London"|
           CITY_NAME == "Edinburgh")
```
```{r}
newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)
```
```{r}
UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)
```
```{r}
Hotels <- Hotels %>%
  group_by(., GSS_CODE, NAME) %>% 
  summarise(`Accomodation count` = unique(hotels_in_borough))
```
```{r}
Airbnb <- Airbnb %>%
  group_by(., GSS_CODE, NAME) %>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
# unique()函数用来去重
```
```{r}
# make the map

# set the breaks
breaks = c(0, 5, 12, 26, 57, 286)

# plot each map
tm1 <- tm_shape(Hotels) +
  tm_polygons("Accomodation count",
              breaks = breaks,
              palette = "PuBu") +
  tm_legend(show = FALSE) +
  tm_layout(frame = FALSE) +
  tm_credits("(a)", position=c(0,0.85), size=1.5)

tm2 <- tm_shape(Airbnb) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

legend <- tm_shape(Hotels) +
    tm_polygons("Accomodation count",
                breaks=breaks,
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))

t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)

t
```
```{r}
library(grid)

grid.newpage()

pushViewport(viewport(layout=grid.layout(2,2)))
print(tm1, vp=viewport(layout.pos.col=1, layout.pos.row=1, height=5))
print(tm2, vp=viewport(layout.pos.col=2, layout.pos.row=1, height=5))
print(tm3, vp=viewport(layout.pos.col=1, layout.pos.row=2, height=5))
print(legend, vp=viewport(layout.pos.col=2, layout.pos.row=2, height=5))
```
## 1.3 inset map
```{r}
Londonbb <- st_bbox(Airbnb,
                    crs = st_crs(Airbnb)) %>%
  st_as_sfc()
```
```{r}
main <- tm_shape(Airbnb, bbbox = Londonbb) +
  tm_polygons("Accomodation count",
              breaks = breaks,
              palette = "PuBu") +
  tm_scale_bar(position = c("left", "bottom"), text.size = .75)+
  tm_layout(legend.position = c("right","top"), 
            legend.text.size=.75, 
            legend.title.size = 1.1,
            frame=FALSE)+
  tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))+
  #tm_text(text = "NAME", size = .5, along.lines =T, remove.overlap=T,  auto.placement=F)+
  tm_compass(type = "8star", position = c(0.06, 0.1)) +

  #bottom left top right
  tm_layout(inner.margin=c(0.02,0.02,0.02,0.2))
```
```{r}
inset = tm_shape(UK_outlinecrop) +
  tm_polygons() +
  tm_shape(Londonbb) +
  tm_borders(col = "grey40", lwd = 3)+
    tm_layout(frame=FALSE,
            bg.color = "transparent")+
  tm_shape(worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1.5, ymod=-0.5)
```
```{r}
main
print(inset, vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))
```
## 1.4 export
```{r}
tmap_save(t, 'hotelsandairbnbR.png')
tmap_save(main, insets_tm = inset,insets_vp=viewport(x=0.86, y=0.29, width=.5, height=.55), filename="test.pdf", dpi=600)
```

## 1.5 basic interactive map
```{r}
tmap_mode("view")
tm_shape(Airbnb) +
  tm_polygons("Accomodation count", breaks=breaks)
```


